import { StyleSheet } from "react-native";
import COLORS from "./Colors";

const stylesBook = StyleSheet.create({
  container: {
    justifyContent: "flex-start",
    width: "100%",
    height: "100%",
    backgroundColor: COLORS.primary,
    paddingTop: 10,
    display: "flex",
  },
  bookDetailsContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginHorizontal: 10,
    backgroundColor: COLORS.base,
  },
  image: {
    maxWidth: 130,
    maxHeight: 175,
    alignSelf: "center",
    borderRadius: 20,
    marginHorizontal: 10,
    marginVertical: 10,
  },
  bookDetails: {
    marginVertical: 10,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    backgroundColor: COLORS.gray3,
  },
  detailLine: {
    flexDirection: "row",
    paddingLeft: 5,
    alignItems: "center",
  },
  detailText: {
    fontSize: 13,
    marginLeft: 5,
    marginBottom: 5,
    color: COLORS.secundary,
  },
  itemContainer: {
    backgroundColor: "rgba(235, 235, 255, .1)",
    alignSelf: "center",
    borderWidth: 0.25,
    borderRadius: 2,
  },
  text: {
    fontSize: 12,
    color: COLORS.secundary,
  },
  follow: {
    fontSize: 18,
    fontStyle: "italic",
    marginBottom: 5,
  },
  textRol: {
    alignSelf: "flex-start",
    textDecorationLine: "underline",
  },
  textButton: {
    alignSelf: "center",
    fontWeight: "bold",
    fontSize: 15,
    color: "white",
    marginLeft: 5,
  },
  buttonF: {
    backgroundColor: "rgba(0, 0, 0, .5)",
    borderWidth: 2,
    borderColor: "black",
    borderRadius: 200,
    width: "100%",
    height: "100%",
    marginRight: 10,
    maxWidth: 35,
    maxHeight: 35,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  buttonD: {
    backgroundColor: "rgba(255, 255 ,255, .75)",
    borderWidth: 2,
    borderColor: "black",
    borderRadius: 200,
    width: "100%",
    height: "100%",
    marginRight: 10,
    marginBottom: 5,
    marginTop: 5,
    maxWidth: 50,
    maxHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  buttonT: {
    flexDirection: "row",
    backgroundColor: "rgba(0, 0, 0, .5)",
    borderWidth: 2,
    borderColor: "black",
    borderRadius: 200,
    marginRight: 5,
    maxWidth: 110,
    maxHeight: 35,
    height: "100%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  rating: {
    marginBottom: 5,
    marginTop: 5,
  },
});

export default stylesBook;
